version: '3'

services:
#  api-metegol:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
#    environment:
#      API_PORT: 8080
  mysql:
    container_name: mysql_metegol
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql